rules:
  - name: "Gluon controls"
    pattern: "com.gluonhq.charm.glisten.control.**"
    includeConstructors: true
    includeMethods: true
    includePublicFields: true

  - name: "FXML Controllers"
    pattern: "dk.belman.gui.**"
    includeConstructors: true
    includeMethods: true
